title: Your awesome title
author:
  name: GitHub User
  email: your-email@domain.com
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description. 
  It will also appear on the site About page. 

plugins:
  - jekyll-paginate
  - jekyll-archives

show_excerpts: false # works (mostly) but applies all formatting from post...not sure how to fix
paginate:      false # set to max posts per page for pagination of post list
paginate_path: /page:num # probably shouldn't touch

jekyll-archives:
  enabled: categories
  layout: posts
  permalinks: '/category/:name'

# jekyll-98 date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
jekyll-98:
  date_format: "%b %-d, %Y"

  # select site icon which will be used for homepage links 
  # on the desktop and in the start menu
  # will also appear on site About page 
  # see assets/icons for choices, omit extension
  
  # icon: computer-2k

  # site_links generate desktop icons (if device width allows)
  # as well as entries in the Start menu (all widths)
  # must have at least title and url
  # icon will default to "document"
  # see assets/icons for choices
  site_links:
  - title: Example 
    url: http://example.com
    target: _blank            # optional
    icon: html                # optional
    alt: 'This is an example' # text will not wrap in start menu; super long alt might make start menu look silly

  # generate social links in footer
  social_links:
    github:  queenkjuul
    youtube: queenkjuul69
    twitch: queenkjuul
    # twitter: jekyllrb
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # keybase: jekyll
    # email: jekyll@jekyll.jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# Build settings
theme: jekyll-98