####  GLOBAL - Site information
# About your website
title: Your awesome title
author: # *** NAME AND EMAIL INCLUDED IN RSS FEED BY DEFAULT ***
  name: &name GitHub User                 # removing &name breaks contact page
  email: &email your-email@domain.com     # removing &email breaks contact page
description: > # > means to ignore newlines until next section
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description. 
  It will also appear on the site About page. 
# url:  https://jekyll-98.github.io             # will try to use github pages url if omitted

#### SETTINGS - Sitewide preferences
remote_theme: queenkjuul/jekyll-98
show_excerpts: true       # mostly works, see README
show_categories: true
paginate:      3          # set to a number of posts per page 
                          # only 3 works well on small mobile screens
                          # set to false to disable pagination (all posts listed on home page)
paginate_path: /page/:num # probably shouldn't touch
# google_analytics:       # input your google analytics key for tracking

#### THEME - Controls for desktop and extra pages
jekyll-98:
  date_format: "%b %-d, %Y" # refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this

  ### SITE ICON
  # select site icon which will be used for homepage links 
  # on the desktop and in the start menu
  # see assets/icons for choices, omit extension
  icon: computer

  ### DESKTOP FOLDERS
  # select which of your post categories should have its own desktop icon
  # should probably try and keep total icons (desktop_categories and site_links)
  # to 7 or less total
  desktop_categories:
    - posts

  ### DESKTOP / START MENU LINKS
  # site_links generate desktop icons (if device width allows)
  # as well as entries in the Start menu (all widths)
  # must have at least title and url
  # icon will default to "document"
  # see assets/icons for icon choices
  site_links:
  - title: Example 
    url: http://example.com
    target: _blank            # optional
    icon: html                # optional
    alt: 'This is an example' # alt text is shown in start menu - long strings won't wrap and might break menu

  ### CONTACT PAGE
  # social links from the social_links section are automatically added to contact page (if enabled)
  # only defined fields are displayed
  contact:        # comment to omit page altogether
    name: *name   # reuses values from above
    email: *email
    phone: phone number if you're spicy 
    address: 
      - 1234 Street Avenue
      - Assigned living quarters number X
      - City, Unit bigger than city, country, postal related code 
      - You can actually add as many lines as your little heart desires
    other:
      - custom info can go here
      - each line gets rendered
      - layout not optimized for long lists

  ### SOCIAL MEDIA / QUICK LAUNCH
  # generate social links in footer
  # only 5 will safely fit on small phones
  social_links:
    github:  queenkjuul
    youtube: queenkjuul69
    twitch: queenkjuul
    # twitter: jekyllrb
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # keybase: jekyll
    # email: jekyll@jekyll.jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

  ### ABOUT PAGE
  # add personal details to about page if you like
  # lines are rendered as bulleted list
  about:
    - Live long and prosper, loves \\//_

#### PLUGINS - Add what you need, but don't remove defaults!
plugins:
  - jekyll-paginate       # theme default
  - jekyll-category-pages # theme-default
  - jekyll-feed           # theme-default

#### DEFAULTS - Only for theme website, you can ignore/remove
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
      categories:
        - posts